#!/bin/sh

# Grab command-line arguments
cmdlnargs="$@"

: ${OO_INSTALL_KEEP_ASSETS:="false"}
: ${OO_INSTALL_CONTEXT:="origin"}
: ${TMPDIR:=/tmp}
[[ $TMPDIR != */ ]] && TMPDIR="${TMPDIR}/"

if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
then
  echo "Checking for necessary tools..."
fi
for i in ruby unzip ssh
do
  command -v $i >/dev/null 2>&1 || { echo >&2 "OpenShift installation requires $i but it does not appear to be available. Correct this and rerun the installer."; exit 1; }
done
if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
then
  echo "...looks good."
fi

# All instances of oo-install-origin-20140515-1427 are replaced during packaging with the actual package name.
if [[ -e ./oo-install-origin-20140515-1427.zip ]]
then
  if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
  then
    echo "Using bundled assets."
  fi
  cp oo-install-origin-20140515-1427.zip ${TMPDIR}/oo-install-origin-20140515-1427.zip
elif [[ $OO_INSTALL_KEEP_ASSETS == 'true' && -e ${TMPDIR}/oo-install-origin-20140515-1427.zip ]]
then
  if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
  then
    echo "Using existing installer assets."
  fi
else
  echo "Downloading oo-install package..."
  curl -s -o ${TMPDIR}oo-install-origin-20140515-1427.zip https://install.openshift.com/origin/oo-install-origin-20140515-1427.zip
fi

if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
then
  echo "Extracting oo-install to temporary directory..."
fi
unzip -qq -o ${TMPDIR}oo-install-origin-20140515-1427.zip -d $TMPDIR

if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
then
  echo "Starting oo-install..."
else
  clear
fi
RUBYDIR='1.9.1/'
RUBYVER=`ruby -v`
if [[ $RUBYVER == ruby\ 1\.8* ]]
then
  RUBYDIR='1.8/'
elif [[ $RUBYVER == ruby\ 2\.* ]]
then
  RUBYDIR=''
fi
GEM_PATH="${TMPDIR}oo-install-origin-20140515-1427/vendor/bundle/ruby/${RUBYDIR}gems/"
RUBYLIB="${TMPDIR}oo-install-origin-20140515-1427/lib:${TMPDIR}oo-install/vendor/bundle"
for i in `ls $GEM_PATH`
do
  RUBYLIB="${RUBYLIB}:${GEM_PATH}${i}/lib/"
done
GEM_PATH=$GEMPATH RUBYLIB=$RUBYLIB OO_INSTALL_CONTEXT=origin OO_VERSION='origin' OO_INSTALL_VERSION='Build 20140515-1427' sh -c "${TMPDIR}oo-install-origin-20140515-1427/bin/oo-install ${cmdlnargs}"

if [ $OO_INSTALL_CONTEXT != 'origin_vm' ]
then
  if [ $OO_INSTALL_KEEP_ASSETS == 'true' ]
  then
    echo "oo-install exited; keeping temporary assets in ${TMPDIR}"
  else
    echo "oo-install exited; removing temporary assets."
    rm -rf ${TMPDIR}oo-install-origin-20140515-1427*
  fi
fi

exit
